//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter39FleetComposerMediaCaptureViewController.h>

#import <T1Twitter/T1CameraCaptureCameraModeRecordViewControllerDelegate-Protocol.h>

@interface _TtC9T1Twitter39FleetComposerMediaCaptureViewController (T1Twitter2) <T1CameraCaptureCameraModeRecordViewControllerDelegate>
- (void)cameraCaptureCameraModeRecordViewController:(id)arg1 didChangeZoomScale:(double)arg2;
- (void)cameraCaptureCameraModeRecordViewControllerDidStartRecording:(id)arg1;
- (void)cameraCaptureCameraModeRecordViewControllerDidStopRecording:(id)arg1;
@end

