//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter22FleetsAnimatableUIView.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter17FleetsStoriesView : _TtC9T1Twitter22FleetsAnimatableUIView
{
    // Error parsing type: , name: bottomVisibility
    // Error parsing type: , name: delegate
    // Error parsing type: , name: didTapAddButton
    // Error parsing type: , name: isActive
    // Error parsing type: , name: account
    // Error parsing type: , name: actionsView
    // Error parsing type: , name: contentView
    // Error parsing type: , name: footerContainer
    // Error parsing type: , name: postProgressView
    // Error parsing type: , name: $__lazy_storage_$_failedFleetView
    // Error parsing type: , name: seenByView
    // Error parsing type: , name: $__lazy_storage_$_bottomGradient
    // Error parsing type: , name: $__lazy_storage_$_failedFleetHeight
    // Error parsing type: , name: entry
    // Error parsing type: , name: _entryState
    // Error parsing type: , name: $__lazy_storage_$_showsFailedFleetView
    // Error parsing type: , name: selectionEmojisView
    // Error parsing type: , name: reactionConfirmationView
    // Error parsing type: , name: reactionOriginFrame
    // Error parsing type: , name: showsActionView
    // Error parsing type: , name: accessibilityScrollAction
    // Error parsing type: , name: accessibilityEscapeAction
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSArray *accessibilityCustomActions;
- (_Bool)accessibilityPerformEscape;
- (_Bool)accessibilityScroll:(long long)arg1;
- (void)seenByAction:(id)arg1;

@end

