//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC17TwitterTextEditor14TextEditorView.h>

#import <T1Twitter/UITextDropDelegate-Protocol.h>

@interface _TtC17TwitterTextEditor14TextEditorView (TwitterTextEditor4) <UITextDropDelegate>
- (id)textDroppableView:(id)arg1 proposalForDrop:(id)arg2;
@end

