//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC9T1TwitterP33_CF645A2B80ECB667A0610C079C1B3AEB25GestureRecognizerDelegate : NSObject
{
    // Error parsing type: , name: shouldBegin
    // Error parsing type: , name: shouldRecognizeSimultaneously
    // Error parsing type: , name: shouldReceiveTouch
    // Error parsing type: , name: shouldRequireFailureOf
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;

@end

