//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC17TwitterTextEditor14TextEditorView.h>

#import <T1Twitter/_TtP17TwitterTextEditor25TextViewTextPasteDelegate_-Protocol.h>

@interface _TtC17TwitterTextEditor14TextEditorView (TwitterTextEditor2) <_TtP17TwitterTextEditor25TextViewTextPasteDelegate_>
- (_Bool)textPasteConfigurationSupporting:(id)arg1 shouldAnimatePasteOfAttributedString:(id)arg2 toRange:(id)arg3;
- (void)textPasteConfigurationSupporting:(id)arg1 transformPasteItem:(id)arg2;
- (_Bool)textPasteConfigurationSupporting:(id)arg1 canPaste:(id)arg2;
@end

