//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1ToastViewModel-Protocol.h>

@class NSString, T1ToastAction;

@interface _TtC9T1Twitter12T1ErrorToast : NSObject <T1ToastViewModel>
{
    // Error parsing type: , name: messageText
    // Error parsing type: , name: iconName
    // Error parsing type: , name: alternateAction
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) T1ToastAction *alternateAction; // @synthesize alternateAction;
@property(nonatomic, readonly) NSString *iconName;
@property(nonatomic, readonly) NSString *messageText;

@end

