//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer;

@interface _TtC9T1TwitterP33_8740323719732FBF5D1B7605EFE2CFA421RotationGuidelineView : UIView
{
    // Error parsing type: , name: guide
    // Error parsing type: , name: lastBounds
}

+ (Class)layerClass;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) CAShapeLayer *layer;

@end

