//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter32DirectMessageSwipeToSendPillView : UIView
{
    // Error parsing type: , name: swipeToSendButton
    // Error parsing type: , name: shouldHighlightSend
    // Error parsing type: , name: hapticFeedbackGenerator
}

- (void).cxx_destruct;
- (void)performHapticFeedback:(unsigned long long)arg1;
- (void)prepareHapticFeedback:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIButton *swipeToSendButton; // @synthesize swipeToSendButton;

@end

