//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _TtCCC9T1Twitter35URTTimelineTopicCollectionViewModel4ItemP33_25869C844ED87B2638D9FB6BE069AA2B13ScribableItem : NSObject
{
    // Error parsing type: , name: scribeItemImpressionID
    // Error parsing type: , name: scribeItem
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSDictionary *scribeItem;
@property(nonatomic, readonly) NSString *scribeItemImpressionID;

@end

