//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TAVUI/_TtC5TAVUI31MediaChromePlayerViewAttachment.h>

@interface _TtC5TAVUI31MediaChromePlayerViewAttachment (TAVUI)
- (void)observerDidDetachFromPlayer:(id)arg1;
- (void)observerDidAttachToPlayer:(id)arg1;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
@end

