//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

#import <T1Twitter/T1DirectMessageTypingIndicatorControllerDelegate-Protocol.h>

@interface _TtC9T1Twitter48DirectMessageConversationTypingIndicatorBehavior : _TtCs12_SwiftObject <T1DirectMessageTypingIndicatorControllerDelegate>
{
    // Error parsing type: , name: typingIndicatorView
    // Error parsing type: , name: typingIndicatorController
    // Error parsing type: , name: delegate
}

- (void)typingIndicatorController:(id)arg1 userDidStopTyping:(id)arg2 didReceiveMessage:(_Bool)arg3;
- (void)typingIndicatorController:(id)arg1 userDidStartTyping:(id)arg2;
- (void)typingIndicatorControllerConversationDidUpdate:(id)arg1;

@end

