//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC17TwitterTextEditor14TextEditorView.h>

#import <T1Twitter/_TtP17TwitterTextEditor16TextViewDelegate_-Protocol.h>

@interface _TtC17TwitterTextEditor14TextEditorView (TwitterTextEditor1) <_TtP17TwitterTextEditor16TextViewDelegate_>
- (void)textView:(id)arg1 didChangeBaseWritingDirection:(long long)arg2 forRange:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
@end

