//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PeriscopeSDK/PTVGuestRoomController-Protocol.h>

@class NSArray, NSString;

@interface PTVGuestRoomBroadcastController : NSObject <PTVGuestRoomController>
{
    _Bool isMuted;
    unsigned long long totalUsersCount;
    NSArray *users;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *users; // @synthesize users;
@property(readonly, nonatomic) unsigned long long totalUsersCount; // @synthesize totalUsersCount;
@property(nonatomic) _Bool isMuted; // @synthesize isMuted;
- (id)guestViewForUser:(id)arg1;
- (void)sendText:(id)arg1 language:(id)arg2;
- (void)sendEmoji:(id)arg1;
- (void)reportUser:(id)arg1;
- (void)blockUser:(id)arg1;
- (void)removeUserAsSpeaker:(id)arg1;
- (void)acceptUserAsSpeaker:(id)arg1;
- (_Bool)canAcceptMoreSpeakers;
- (void)switchAsListener;
- (void)cancelSwitchAsSpeaker;
- (void)switchAsSpeaker;
- (void)joinExistingRoomWithRoomID:(id)arg1;
- (void)createNewRoom;
- (void)removeGuestRoomControllerObserver:(id)arg1;
- (void)addGuestRoomControllerObserver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

