//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString, TFNTwitterAccount;
@protocol OS_dispatch_queue;

@interface T1ArchivedVisitedLinkService : NSObject
{
    _Bool _hasLoadedFromDisk;
    NSString *_visitedLinksCacheFile;
    TFNTwitterAccount *_account;
    NSMutableSet *_visitedLinksSet;
    NSObject<OS_dispatch_queue> *_concurrentLinksQueue;
}

+ (void)purgeAllLinksFromDisk;
+ (id)registeredServices;
+ (id)sharedInstanceForAccount:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool hasLoadedFromDisk; // @synthesize hasLoadedFromDisk=_hasLoadedFromDisk;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *concurrentLinksQueue; // @synthesize concurrentLinksQueue=_concurrentLinksQueue;
@property(retain) NSMutableSet *visitedLinksSet; // @synthesize visitedLinksSet=_visitedLinksSet;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void)_t1_pruneExpiredVisitedLinks;
- (void)loadLinksFromDisk;
- (void)saveLinksToDisk;
@property(readonly, nonatomic) NSString *visitedLinksCacheFile; // @synthesize visitedLinksCacheFile=_visitedLinksCacheFile;
- (_Bool)isValidLink:(id)arg1;
- (_Bool)hasVisitedLink:(id)arg1;
- (_Bool)isLinkNewsArticle:(id)arg1;
- (id)initWithAccount:(id)arg1;

@end

