//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1UIActivity.h>

@class TFNTwitterStatus;

@interface T1CopyLinkActivity : T1UIActivity
{
    TFNTwitterStatus *_status;
}

- (void).cxx_destruct;
- (void)performActivity;
- (id)activityType;
- (_Bool)isSupported;
- (id)initWithStatus:(id)arg1;

@end

