//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface T1ConversationDetailsSettings : NSObject
{
}

+ (id)colorWithHexString:(id)arg1;
+ (id)colorWithRGBHex:(unsigned int)arg1;
+ (_Bool)selectedStateTapExtendedSendReplyButtonNoOpEnabled;
+ (_Bool)selectedStateTapInlineActionsViewNoOpEnabled;
+ (_Bool)selectedStateTapInlineReplyViewNoOpEnabled;
+ (_Bool)maximumIndentationSentWithCursorsEnabled;
+ (_Bool)emphasizedConnectorLinesEnabled;
+ (double)inlineActionRightMargin;
+ (_Bool)inlineActionsVerticallyAligned;
+ (double)selectedStateShadowOffsetHeight;
+ (double)selectedStateShadowOffsetWidth;
+ (double)selectedStateStrokeWidth;
+ (double)selectedStateShadowOpacity;
+ (double)selectedStateShadowRadius;
+ (_Bool)longPressCopyForSelectedStateOnly;
+ (_Bool)floatingReplyBarHiddenForSelectedInlineReplyBar;
+ (_Bool)replyInlineActionFocusesInTwoSteps;
+ (_Bool)replyInlineActionFocusesInlineReply;
+ (_Bool)assertOnDuplicateItems;
+ (_Bool)enableConnectorLinesToSelectedStateContainer;
+ (_Bool)disableRootAttachedThread;
+ (_Bool)focalIsInitiallySelected;
+ (_Bool)selectedAnimationAlwaysKeepFullTweetOnscreen;
+ (_Bool)selectedAnimationScrollTextStable;
+ (_Bool)tapToCollapseEnabled;
+ (_Bool)tweetTextSelectionEnabled;
+ (_Bool)showOverflowButtonsOnTombstones;
+ (_Bool)conversationOverflowIncludedInGQLQueryEnabled;
+ (_Bool)alwaysShowAQCursors;
+ (_Bool)alwaysShowLQCursors;
+ (_Bool)showMoreGrayThemeEnabled;
+ (_Bool)showMoreExpandedHitTestingEnabled;
+ (_Bool)showMoreCoalescingDebugLabelsEnabled;
+ (long long)showMoreCoalescingLoadLimit;
+ (_Bool)showMoreCoalescingEnabled;
+ (_Bool)conversationThreadingCollapseEnabled;
+ (id)connectorEmphasisColorDark;
+ (id)connectorEmphasisColor;
+ (_Bool)connectorEmphasisCustomColorsEnabled;
+ (_Bool)connectorEmphasisDirectDescendentsOnly;
+ (_Bool)connectorEmphasisDirectAncestorOnly;
+ (_Bool)connectorEmphasisInBlueEnabled;

@end

