//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1ConversationContainerViewController.h>

#import <T1Twitter/T1TweetDetailsPresenting-Protocol.h>

@interface T1ConversationContainerViewController (T1Twitter4) <T1TweetDetailsPresenting>
- (void)presentTweetWithID:(long long)arg1;
- (_Bool)canPresentTweetWithID:(long long)arg1;
@end

