//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageComposeViewController.h>

#import <T1Twitter/T1DirectMessageComposeTextViewDelegate-Protocol.h>

@interface T1DirectMessageComposeViewController (T1Twitter8) <T1DirectMessageComposeTextViewDelegate>
- (_Bool)handlePasteImageForComposeTextView:(id)arg1;
- (_Bool)imagePasteEnabledForComposeTextView:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
@end

