//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageComposeViewController.h>

@class NSArray;

@interface T1DirectMessageComposeViewController (T1Twitter10)
- (void)handleSendMessageKeyCommand;
- (void)handleSelectKeyCommand;
- (void)handleReplyToMessageKeyCommand;
- (void)handleLineUpKeyCommand;
- (void)handleLineDownKeyCommand;
@property(nonatomic, readonly) NSArray *keyCommands;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
@end

