//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageComposeViewController.h>

#import <T1Twitter/T1AltTextViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1MediaAttachmentsViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNModalContainerViewControllerDelegate-Protocol.h>

@interface T1DirectMessageComposeViewController (T1Twitter2) <T1MediaAttachmentsViewControllerDelegate, T1AltTextViewControllerDelegate, TFNModalContainerViewControllerDelegate>
- (void)attachmentsViewControllerDidTapBackground:(id)arg1;
- (void)attachmentsViewController:(id)arg1 didTapRemoveAttachment:(id)arg2;
- (void)altTextViewController:(id)arg1 didCompleteWithAltText:(id)arg2;
- (void)altTextViewControllerDidCancel:(id)arg1;
- (void)attachmentsViewController:(id)arg1 didTapLivePhotoToggleButton:(id)arg2;
- (void)attachmentsViewController:(id)arg1 didTapAltTextForAttachment:(id)arg2;
- (void)attachmentsViewController:(id)arg1 didTapAttachment:(id)arg2;
- (double)visibleLowerBoundForAttachmentsViewController:(id)arg1;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowLivePhotoToggleButtonForAttachment:(id)arg2;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowAltTextButtonForAttachment:(id)arg2;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowEditButtonForAttachment:(id)arg2;
@end

