//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageComposeViewController.h>

#import <T1Twitter/T1PhotoGalleryViewControllerDelegate-Protocol.h>

@interface T1DirectMessageComposeViewController (T1Twitter2) <T1PhotoGalleryViewControllerDelegate>
- (void)photoGalleryViewController:(id)arg1 didEndSessionWithAttachments:(id)arg2;
- (void)photoGalleryViewControllerDidCancelSession:(id)arg1;
@end

