//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageComposeViewController.h>

@interface T1DirectMessageComposeViewController (T1Twitter11)
- (void)quickReplyPresentationBehaviorHideQuickReply:(id)arg1;
- (void)quickReplyPresentationBehavior:(id)arg1 presentOptionsQuickReplyWithID:(id)arg2 options:(id)arg3 selectedOption:(id)arg4 shouldFocus:(_Bool)arg5;
@end

