//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface T1FlexibleLayoutHelper : NSObject
{
}

+ (CDUnknownBlockType)matchPreviousLayoutFrameCalculator;
+ (CDUnknownBlockType)topRightLayoutFrameCalculator;
+ (CDUnknownBlockType)flowLayoutFrameCalculator;
+ (CDUnknownBlockType)verticallyCenteredHorizontalLayoutFrameCalculator;
+ (CDUnknownBlockType)horizontallyCenteredVerticalLayoutFrameCalculator;
+ (CDUnknownBlockType)fullWidthVerticalLayoutFrameCalculator;
+ (CDUnknownBlockType)topAlignedHorizontalLayoutFrameCalculator;
+ (CDUnknownBlockType)leftAlignedVerticalLayoutFrameCalculator;
- (struct CGRect)layoutItems:(id)arg1 inBounds:(struct CGRect)arg2 withLayoutMetrics:(id)arg3 forSizing:(_Bool)arg4 visibilityHandler:(CDUnknownBlockType)arg5 frameHandler:(CDUnknownBlockType)arg6;

@end

