//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface T1InlineVideoViewGestureResponder : NSObject
{
    // Error parsing type: , name: onTapBlock
    // Error parsing type: , name: onLongPressBlock
}

- (void).cxx_destruct;
- (id)init;
- (void)onLongPress;
- (void)onTap;
- (id)initOnTapBlock:(CDUnknownBlockType)arg1 onLongPressBlock:(CDUnknownBlockType)arg2;

@end

