//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1InlineVideoView.h>

@class NSString;

@interface T1InlineVideoView (T1Twitter)
@property(nonatomic, readonly) NSString *debugDescription;
- (void)updateViewModelWith:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 imageFetchHelper:(id)arg4;
@end

