//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/ASWebAuthenticationPresentationContextProviding-Protocol.h>
#import <T1Twitter/T1LoginChallengeProtocol-Protocol.h>

@class ASWebAuthenticationSession, NSString, UIViewController;

@interface T1LoginChallengeWebAuthSession : NSObject <ASWebAuthenticationPresentationContextProviding, T1LoginChallengeProtocol>
{
    CDUnknownBlockType _didAddAccountBlock;
    UIViewController *_presentationAnchor;
    ASWebAuthenticationSession *_session;
}

+ (_Bool)isAuthenticationInProgress;
- (void).cxx_destruct;
@property(readonly, nonatomic) ASWebAuthenticationSession *session; // @synthesize session=_session;
@property(nonatomic) __weak UIViewController *presentationAnchor; // @synthesize presentationAnchor=_presentationAnchor;
@property(copy, nonatomic) CDUnknownBlockType didAddAccountBlock; // @synthesize didAddAccountBlock=_didAddAccountBlock;
- (id)presentationAnchorForWebAuthenticationSession:(id)arg1;
- (void)presentLoginChallengeFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)cancel;
- (void)start;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

