//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewAdapter.h>

@class UIFont;

@interface T1NudgeItemViewAdapter : TFNItemsDataViewAdapter
{
    UIFont *_titleLabelFont;
    UIFont *_subtitleLabelFont;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIFont *subtitleLabelFont; // @synthesize subtitleLabelFont=_subtitleLabelFont;
@property(retain, nonatomic) UIFont *titleLabelFont; // @synthesize titleLabelFont=_titleLabelFont;
- (id)_t1_subtitleForItem:(id)arg1;
- (id)_t1_titleForItem:(id)arg1;
- (id)_t1_iconForItem:(id)arg1;
- (id)_t1_nudgeCellForItem:(id)arg1 atIndexPath:(id)arg2 withController:(id)arg3;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

