//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNTableViewCell.h>

@class UIColor, UIImageView, UILabel, UIStackView, UIView;

@interface T1NudgeItemCell : TFNTableViewCell
{
    double _contentVerticalSpacing;
    UIColor *_nudgeBackgroundColor;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIView *_cardView;
    UIView *_nudgeContainerView;
    UIStackView *_expandedStackView;
    struct UIEdgeInsets _contentEdgeInsets;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) struct UIEdgeInsets contentEdgeInsets; // @synthesize contentEdgeInsets=_contentEdgeInsets;
@property(retain, nonatomic) UIStackView *expandedStackView; // @synthesize expandedStackView=_expandedStackView;
@property(retain, nonatomic) UIView *nudgeContainerView; // @synthesize nudgeContainerView=_nudgeContainerView;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIColor *nudgeBackgroundColor; // @synthesize nudgeBackgroundColor=_nudgeBackgroundColor;
@property(nonatomic) double contentVerticalSpacing; // @synthesize contentVerticalSpacing=_contentVerticalSpacing;
- (void)_t1_setArrangedSubviews;
- (double)_t1_labelPreferredMaxLayoutWidthForSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)_t1_addAndConstrainSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

