//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TFNTwitterAccount, TFNTwitterStatus, UIColor;

@interface T1NudgeItem : NSObject
{
    long long _style;
    NSString *_iconName;
    NSString *_condensedTitle;
    NSString *_title;
    NSString *_subtitle;
    TFNTwitterStatus *_status;
    TFNTwitterAccount *_account;
    double _contentVerticalSpacing;
    UIColor *_backgroundColor;
    UIColor *_iconImageColor;
    struct CGSize _iconImageSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *iconImageColor; // @synthesize iconImageColor=_iconImageColor;
@property(nonatomic) struct CGSize iconImageSize; // @synthesize iconImageSize=_iconImageSize;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double contentVerticalSpacing; // @synthesize contentVerticalSpacing=_contentVerticalSpacing;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *condensedTitle; // @synthesize condensedTitle=_condensedTitle;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(nonatomic) long long style; // @synthesize style=_style;
- (id)initWithIconName:(id)arg1 condensedTitle:(id)arg2 title:(id)arg3 subtitle:(id)arg4 status:(id)arg5 account:(id)arg6 style:(long long)arg7;
- (id)initWithIconName:(id)arg1 title:(id)arg2 subtitle:(id)arg3 status:(id)arg4 account:(id)arg5;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 status:(id)arg3 account:(id)arg4;
- (id)initWithIconName:(id)arg1 title:(id)arg2 subtitle:(id)arg3;
- (id)initWithIconName:(id)arg1 title:(id)arg2;
- (id)initWithIconName:(id)arg1 condensedTitle:(id)arg2;

@end

