//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, T1FlexibleLayoutView, TFNActivityIndicatorButton, UIBarButtonItem, UIButton, UIView;

@interface T1OnboardingFooterViewModel : NSObject
{
    NSString *_nextLabel;
    NSString *_skipLabel;
    T1FlexibleLayoutView *_footerView;
    long long _format;
    NSArray *_dataViewItems;
    UIBarButtonItem *_nextBarButtonItem;
    TFNActivityIndicatorButton *_nextButton;
    UIBarButtonItem *_skipBarButtonItem;
    UIButton *_skipButton;
    NSArray *_toolbarItems;
}

- (void).cxx_destruct;
- (long long)private_formatForSupportedFormats:(long long)arg1 style:(long long)arg2;
@property(readonly, nonatomic) NSArray *toolbarItems; // @synthesize toolbarItems=_toolbarItems;
@property(readonly, nonatomic) UIBarButtonItem *skipBarButtonItem; // @synthesize skipBarButtonItem=_skipBarButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *nextBarButtonItem; // @synthesize nextBarButtonItem=_nextBarButtonItem;
@property(readonly, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(readonly, nonatomic) TFNActivityIndicatorButton *nextButton; // @synthesize nextButton=_nextButton;
@property(readonly, nonatomic) UIView *footerView;
@property(readonly, nonatomic) NSArray *dataViewItems; // @synthesize dataViewItems=_dataViewItems;
- (id)initWithStyle:(long long)arg1 supportedFormats:(long long)arg2 footerSpec:(id)arg3;
- (id)initWithStyle:(long long)arg1 supportedFormats:(long long)arg2 nextLabel:(id)arg3 skipLabel:(id)arg4;

@end

