//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1UIActivity.h>

#import <T1Twitter/MFMailComposeViewControllerDelegate-Protocol.h>

@class MFMailComposeViewController, NSString, TFNTwitterStatus, UIViewController;

@interface T1ShareToMailActivity : T1UIActivity <MFMailComposeViewControllerDelegate>
{
    TFNTwitterStatus *_status;
    UIViewController *_presenterViewController;
    MFMailComposeViewController *_mailComposeViewController;
}

- (void).cxx_destruct;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)performActivity;
- (_Bool)isSupported;
- (id)initWithStatus:(id)arg1 presenterViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

