//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol T1SpheresUserSettingsRepositoryDelegate;

@interface T1SpheresUserSettingsRepository : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: accountID
    // Error parsing type: , name: pinnedArchiver
    // Error parsing type: , name: rankingModeArchiver
    // Error parsing type: , name: viewModelsFuture
    // Error parsing type: , name: persistentListObservers
    // Error parsing type: , name: durableStorageHelper
    // Error parsing type: , name: persistentPinnedListsObserver
    // Error parsing type: , name: latestObservedModel
}

- (void).cxx_destruct;
- (id)init;
- (void)didRemoveAccount:(id)arg1;
- (_Bool)isLatestRankingModeActiveForListID:(long long)arg1 memberCount:(long long)arg2;
- (void)setIsLatestRankingModeActive:(_Bool)arg1 forListID:(long long)arg2 andPersistData:(_Bool)arg3;
- (void)unarchiveSphereViewModelsWithCompletion:(CDUnknownBlockType)arg1;
- (void)archiveSphereViewModels:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadInitialPinnedListModels;
- (id)initWithAccount:(id)arg1;
@property(nonatomic) __weak id <T1SpheresUserSettingsRepositoryDelegate> delegate; // @synthesize delegate;

@end

