//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNComposableViewAdapter.h>

#import <T1Twitter/T1TimelinesItemProminentSocialContextViewDelegate-Protocol.h>

@class NSString;

@interface T1StandardStatusProminentSocialContextViewAdapter : TFNComposableViewAdapter <T1TimelinesItemProminentSocialContextViewDelegate>
{
}

- (id)_t1_handleEventWithType:(id)arg1 sender:(id)arg2;
- (id)previewConfigurationForSocialContextView:(id)arg1;
- (void)prominentSocialContextView:(id)arg1 didTapToggleTopicFollowButtonWithViewModel:(id)arg2;
- (void)_t1_prominentSocialContextView:(id)arg1 toggleTopicFollowStateWithViewModel:(id)arg2;
- (void)prominentSocialContextView:(id)arg1 unfollowWithViewModel:(id)arg2;
- (void)prominentSocialContextView:(id)arg1 followWithViewModel:(id)arg2;
- (void)socialContextView:(id)arg1 didTapCaret:(id)arg2;
- (void)socialContextViewDidTap:(id)arg1;
- (id)_t1_socialBadgeColorForName:(id)arg1;
- (void)_t1_postTopicFollowingChangeNotificationForViewModel:(id)arg1;
- (void)_t1_toggleTopicFollowUIState:(id)arg1 forViewModel:(id)arg2;
- (void)_t1_updateView:(id)arg1 forViewModel:(id)arg2;
- (id)_t1_viewModelWithToggledTopicFollowState:(id)arg1;
- (id)_t1_socialContextViewModelForStatusViewModel:(id)arg1;
- (_Bool)isLayoutState:(id)arg1 validForViewModel:(id)arg2 layoutMetrics:(id)arg3;
- (struct CGSize)_t1_followButtonSize;
- (struct CGSize)_t1_followedButtonSize;
- (struct CGSize)_t1_minFollowButtonSize;
- (struct CGSize)_t1_maxFollowButtonSize;
- (id)layoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (id)legacyLayoutStateForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (void)viewModel:(id)arg1 didUpdateWithInfo:(id)arg2 forView:(id)arg3;
- (void)setViewModel:(id)arg1 forView:(id)arg2;
- (void)view:(id)arg1 willMoveToHostView:(id)arg2;
- (id)initializeView;
- (_Bool)shouldBeVisibleForViewModel:(id)arg1;
- (void)layoutSocialContextAboveContentWithLayoutState:(id)arg1;
- (void)accessibilityPerformTapFollowTopicAction:(id)arg1 viewModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

