//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont, UIImage, UIImageView, UILabel;

@interface T1TweetDetailsConversationControlContextView : UIView
{
    UIImageView *_badgeImageView;
    UILabel *_textLabel;
    UILabel *_titleLabel;
}

+ (struct CGSize)sizeWithTitleText:(id)arg1 titleFont:(id)arg2 LabelText:(id)arg3 labelFont:(id)arg4 maximumWidth:(double)arg5;
- (void).cxx_destruct;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(readonly, nonatomic) UIImageView *badgeImageView; // @synthesize badgeImageView=_badgeImageView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImage *badgeImage;
@property(retain, nonatomic) UIFont *textFont;
@property(retain, nonatomic) UIColor *textColor;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) UIColor *titleColor;
@property(retain, nonatomic) UIFont *titleFont;
@property(copy, nonatomic) NSString *title;
- (void)_t1_tweetDetailsConversationControlContextView_initialize;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

