//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class T1UIActivity, TFNTwitterStatus;

@protocol T1UIActivityDelegate
- (void)activity:(T1UIActivity *)arg1 didShareTwitterStatus:(TFNTwitterStatus *)arg2 success:(_Bool)arg3;
@end

