//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1VoicePlaybackView.h>

@class NSArray, NSLayoutConstraint, NSTimer, T1AmbientNotificationContainer, T1AvatarImageView, T1VoiceDockViewModel, TAVPlaybackState, TFNBarProgressView, TFNPaddedButton, TFNSolidColorView, UIButton, UIImage, UILabel, UIPanGestureRecognizer, UIStackView, UIView;
@protocol T1VoiceDockViewDelegate;

@interface T1VoiceDockView : T1VoicePlaybackView
{
    id <T1VoiceDockViewDelegate> _delegate;
    T1VoiceDockViewModel *_viewModel;
    TFNSolidColorView *_animationWrapper;
    NSArray *_animationConstraints;
    TFNBarProgressView *_progressView;
    TAVPlaybackState *_lastKnownPlaybackState;
    TFNPaddedButton *_progressThumbView;
    NSLayoutConstraint *_progressThumbViewCenterXConstraint;
    UIPanGestureRecognizer *_progressThumbViewPanGesture;
    NSTimer *_hideProgressThumbViewTimer;
    UIButton *_backgroundButton;
    UIButton *_closeButton;
    UIButton *_playPauseButton;
    T1AvatarImageView *_imageView;
    UIStackView *_descriptionStackView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIView *_topDivider;
    UIView *_bottomDivider;
    T1AmbientNotificationContainer *_playbackErrorNotificationContainer;
    struct CGPoint _progressThumbOriginalPosition;
}

+ (id)new;
- (void).cxx_destruct;
@property(retain, nonatomic) T1AmbientNotificationContainer *playbackErrorNotificationContainer; // @synthesize playbackErrorNotificationContainer=_playbackErrorNotificationContainer;
@property(retain, nonatomic) UIView *bottomDivider; // @synthesize bottomDivider=_bottomDivider;
@property(retain, nonatomic) UIView *topDivider; // @synthesize topDivider=_topDivider;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIStackView *descriptionStackView; // @synthesize descriptionStackView=_descriptionStackView;
@property(retain, nonatomic) T1AvatarImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(retain, nonatomic) NSTimer *hideProgressThumbViewTimer; // @synthesize hideProgressThumbViewTimer=_hideProgressThumbViewTimer;
@property(nonatomic) struct CGPoint progressThumbOriginalPosition; // @synthesize progressThumbOriginalPosition=_progressThumbOriginalPosition;
@property(retain, nonatomic) UIPanGestureRecognizer *progressThumbViewPanGesture; // @synthesize progressThumbViewPanGesture=_progressThumbViewPanGesture;
@property(retain, nonatomic) NSLayoutConstraint *progressThumbViewCenterXConstraint; // @synthesize progressThumbViewCenterXConstraint=_progressThumbViewCenterXConstraint;
@property(retain, nonatomic) TFNPaddedButton *progressThumbView; // @synthesize progressThumbView=_progressThumbView;
@property(retain, nonatomic) TAVPlaybackState *lastKnownPlaybackState; // @synthesize lastKnownPlaybackState=_lastKnownPlaybackState;
@property(retain, nonatomic) TFNBarProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSArray *animationConstraints; // @synthesize animationConstraints=_animationConstraints;
@property(retain, nonatomic) TFNSolidColorView *animationWrapper; // @synthesize animationWrapper=_animationWrapper;
@property(retain, nonatomic) T1VoiceDockViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <T1VoiceDockViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (void)_t1_hidePlaybackErrorIfNeeded;
- (void)_t1_showPlaybackError:(id)arg1;
@property(nonatomic) double progress;
- (void)_t1_replaceAnimatingConstraintsWithConstraints:(id)arg1;
- (void)animateDismissal:(CDUnknownBlockType)arg1;
- (void)animateDocking:(CDUnknownBlockType)arg1;
- (_Bool)_t1_isScrubbing;
- (void)_t1_hideScrubbingAfterDelay:(double)arg1;
- (void)_t1_setScrubbingVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_handlePanEvent:(id)arg1;
- (void)_t1_handleTapEvent:(id)arg1;
@property(readonly, nonatomic) UIImage *avatarImage;
- (void)dealloc;
- (id)initWithImagePipeline:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

