//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1VoiceDockView;

@protocol T1VoiceDockViewDelegate <NSObject>
- (void)voiceDockViewDidInvalidateLayout:(T1VoiceDockView *)arg1;
- (void)voiceDockView:(T1VoiceDockView *)arg1 didSeekToTimeSecs:(double)arg2;
- (void)voiceDockViewCloseButtonWasTapped:(T1VoiceDockView *)arg1;
- (void)voiceDockViewPlayPauseButtonWasTapped:(T1VoiceDockView *)arg1;
- (void)voiceDockViewWasTapped:(T1VoiceDockView *)arg1;
@end

