//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1Dockable-Protocol.h>
#import <T1Twitter/T1DockingControllerDelegate-Protocol.h>
#import <T1Twitter/T1VoiceDockViewControllerContainer-Protocol.h>
#import <T1Twitter/T1VoiceDockViewDelegate-Protocol.h>

@class NSMutableArray, NSString, UIView, UIViewController;
@protocol T1VoiceDockableViewController, TFNTwitterCardDataSource;

@interface T1VoiceDockViewController : TFNViewController <T1VoiceDockViewDelegate, T1VoiceDockViewControllerContainer, T1Dockable, T1DockingControllerDelegate>
{
    NSMutableArray *_contentViewControllers;
}

+ (id)currentVoiceDockViewControllerMakeIfNeededOnWindow:(id)arg1 userAction:(long long)arg2;
+ (id)currentVoiceDockViewController;
+ (id)new;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *contentViewControllers; // @synthesize contentViewControllers=_contentViewControllers;
- (void)voiceDockableViewControllerCanResignAudioFocus:(id)arg1;
- (void)voiceDockableViewControllerRequestedAudioFocus:(id)arg1;
- (void)voiceDockableViewControllerHasEndedSession:(id)arg1;
- (_Bool)voiceDockableViewControllerExpandIfAble:(id)arg1;
- (void)voiceDockViewDidInvalidateLayout:(id)arg1;
@property(readonly, nonatomic) double preferredPinnedHeight;
@property(readonly, nonatomic) long long dockableStyle;
@property(readonly, nonatomic) NSString *playerIdentifier;
@property(readonly, nonatomic) _Bool isDockedVideoPlaying;
@property(readonly, nonatomic) _Bool isDockedVideoPaused;
- (void)muteDockedVideo:(_Bool)arg1;
- (void)pauseDockedVideo;
- (void)playDockedVideo;
@property(readonly, nonatomic) _Bool dockedViewContainsVideo;
@property(readonly, nonatomic) long long dockedViewSwipeAction;
@property(readonly, nonatomic) long long dockedViewTapAction;
@property(readonly, nonatomic) CDUnknownBlockType undockActionBlock;
@property(readonly, nonatomic) UIView *dockableView;
- (id)popVoiceDockViewController;
- (void)removeVoiceDockViewController:(id)arg1;
- (void)pushVoiceDockViewController:(id)arg1;
@property(readonly, nonatomic) UIViewController<T1VoiceDockableViewController> *baseContentViewController;
@property(readonly, nonatomic) UIViewController<T1VoiceDockableViewController> *topContentViewController;
- (id)_t1_dockView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) id <TFNTwitterCardDataSource> cardDataSource;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

