//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TAEAppearance : NSObject
{
}

+ (void)_tae_setupItemsAppearance;
+ (void)_tae_setupStringDataViewAdapterFonts;
+ (void)_tae_setupBarButtonSystemItemOverrides;
+ (void)_tae_setupButtonAppearance;
+ (void)_tae_setupTFNUI;
+ (void)_tae_setupUIAppearance;
+ (void)_tae_setupVectorImages;
+ (void)setAdditionalVectorImageSearchDirectoryURLs:(id)arg1;
+ (void)setupAppearance;
+ (id)_tae_barButtonItemTextAttributesWithFont:(id)arg1;
+ (void)setupToolbarAppearance:(id)arg1 customShadowColor:(id)arg2 barTintColor:(id)arg3 itemTintColor:(id)arg4;
+ (void)setupTextBarButtonItemAppearance:(id)arg1 font:(id)arg2 textTintColor:(id)arg3;
+ (void)setupImageBarButtonItemButtonAppearance:(id)arg1 imageTintColor:(id)arg2;
+ (void)setupBackButtonAppearance:(id)arg1 tintColor:(id)arg2;
+ (void)setupNavigationBarAppearance:(id)arg1 customShadowColor:(id)arg2 translucent:(_Bool)arg3 barTintColor:(id)arg4 itemTintColor:(id)arg5 titleColor:(id)arg6 statusBarStyle:(long long)arg7;

@end

