//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNUIConfiguration.h>

@class TAETFNUIColorPaletteAdapter, TAETFNUIFontGroupAdapter;

@interface TAETFNUIConfiguration : TFNUIConfiguration
{
    TAETFNUIColorPaletteAdapter *_colorPaletteAdapter;
    TAETFNUIFontGroupAdapter *_fontGroupAdapter;
}

- (void).cxx_destruct;
- (id)buttonFontGroup;
- (id)fontGroup;
- (id)colorPalette;
- (id)init;

@end

