//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/SKStoreProductViewControllerDelegate-Protocol.h>

@class NSString, TFSTwitterScribeContext;
@protocol TFSTwitterLegacyScribeLogMethods;

@interface TAFStoreProductViewControllerDelegate : NSObject <SKStoreProductViewControllerDelegate>
{
    id <TFSTwitterLegacyScribeLogMethods> _scribe;
    TFSTwitterScribeContext *_scribeContext;
    double _startedAt;
}

- (void).cxx_destruct;
@property(nonatomic) double startedAt; // @synthesize startedAt=_startedAt;
@property(copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(retain, nonatomic) id <TFSTwitterLegacyScribeLogMethods> scribe; // @synthesize scribe=_scribe;
- (void)productViewControllerDidFinish:(id)arg1;
- (id)initWithScribe:(id)arg1 scribeContext:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

