//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIMenu;

@interface TFNMenuCompatibleControl : UIControl
{
    UIMenu *_menu;
    CDUnknownBlockType _willDismissMenuBlock;
    struct CGPoint _menuAttachmentPoint;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType willDismissMenuBlock; // @synthesize willDismissMenuBlock=_willDismissMenuBlock;
@property(nonatomic) struct CGPoint menuAttachmentPoint; // @synthesize menuAttachmentPoint=_menuAttachmentPoint;
@property(retain, nonatomic) UIMenu *menu; // @synthesize menu=_menu;
- (struct CGPoint)menuAttachmentPointForConfiguration:(id)arg1;
- (void)contextMenuInteraction:(id)arg1 willEndForConfiguration:(id)arg2 animator:(id)arg3;
- (id)contextMenuInteraction:(id)arg1 configurationForMenuAtLocation:(struct CGPoint)arg2;

@end

