//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor;

@interface TFNMenuCenteredIconItem : NSObject
{
    NSString *_iconImageName;
    UIColor *_iconFillColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *iconFillColor; // @synthesize iconFillColor=_iconFillColor;
@property(copy, nonatomic) NSString *iconImageName; // @synthesize iconImageName=_iconImageName;
- (id)initWithIconImageName:(id)arg1;

@end

