//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterUnifiedCardBaseComponentModel.h>

#import <T1Twitter/TFNTwitterUnifiedCardAppMetadataAdaptable-Protocol.h>
#import <T1Twitter/TFNTwitterUnifiedCardCTAButtonVariationsAdaptable-Protocol.h>
#import <T1Twitter/TFNTwitterUnifiedCardDetailsAdaptable-Protocol.h>

@class NSArray, NSString, TFNTwitterUnifiedCardAppMetadataConfig, TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap, TFNTwitterUnifiedCardButtonData, TFNTwitterUnifiedCardDestinationModel, TFNTwitterUnifiedCardDominantColorConfig;

@interface TFNTwitterUnifiedCardAppStoreDetailsComponentModel : TFNTwitterUnifiedCardBaseComponentModel <TFNTwitterUnifiedCardDetailsAdaptable, TFNTwitterUnifiedCardAppMetadataAdaptable, TFNTwitterUnifiedCardCTAButtonVariationsAdaptable>
{
    TFNTwitterUnifiedCardDominantColorConfig *_dominantColorConfig;
    TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap *_platformMap;
    TFNTwitterUnifiedCardButtonData *_button;
    TFNTwitterUnifiedCardAppMetadataConfig *_appMetadataConfig;
}

+ (id)componentWithJSON:(id)arg1 destinationDict:(id)arg2 mediaEntitiesDict:(id)arg3 appStoreData:(id)arg4 promotedContent:(id)arg5 usersDict:(id)arg6;
- (void).cxx_destruct;
@property(retain, nonatomic) TFNTwitterUnifiedCardAppMetadataConfig *appMetadataConfig; // @synthesize appMetadataConfig=_appMetadataConfig;
@property(readonly, nonatomic) TFNTwitterUnifiedCardButtonData *button; // @synthesize button=_button;
@property(retain, nonatomic) TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap *platformMap; // @synthesize platformMap=_platformMap;
@property(readonly, nonatomic) TFNTwitterUnifiedCardDominantColorConfig *dominantColorConfig; // @synthesize dominantColorConfig=_dominantColorConfig;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long appRatingsType;
@property(readonly, copy, nonatomic) NSString *ratingCount;
@property(readonly, copy, nonatomic) NSString *ratingStars;
@property(readonly, nonatomic) long long appMetadataLineTwoType;
@property(readonly, nonatomic) _Bool isFreeApp;
@property(readonly, nonatomic) _Bool isEditorsChoice;
@property(readonly, nonatomic) _Bool shouldUseSingleLineTitle;
@property(readonly, nonatomic) _Bool shouldShowAppIcon;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithDestination:(id)arg1 shouldRenderFullBleed:(_Bool)arg2 platformMap:(id)arg3 appMetadataConfig:(id)arg4 dominantColorConfig:(id)arg5;
- (id)initWithComponentJSON:(id)arg1 destinationDict:(id)arg2 platformMap:(id)arg3;
- (id)withButton:(id)arg1;
- (id)withPromotedContent:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSArray *axDestinations;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) TFNTwitterUnifiedCardDestinationModel *destination;
@property(readonly, nonatomic) _Bool shouldRenderFullBleed;
@property(readonly) Class superclass;

@end

