//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterURTTimelineStatusBanner.h>

@class NSString;

@interface TFNTwitterURTTimelineStatusTopicBanner : TFNTwitterURTTimelineStatusBanner
{
    _Bool _isFollowingTopic;
    NSString *_topicId;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isFollowingTopic; // @synthesize isFollowingTopic=_isFollowingTopic;
@property(readonly, copy, nonatomic) NSString *topicId; // @synthesize topicId=_topicId;
- (id)landingURL;
- (id)associatedTopicId;
- (void)_tfn_handleTopicToggleUpdateNotification:(id)arg1;
- (void)dealloc;
- (id)initWithBannerText:(id)arg1 badgeName:(id)arg2 topicId:(id)arg3 isFollowingTopic:(_Bool)arg4;

@end

