//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterAppearance/NSObject-Protocol.h>

@class UIColor;

@protocol TFNUIColorPalette <NSObject>
@property(readonly, nonatomic) UIColor *cellAccessorySuccessColor;
@property(readonly, nonatomic) UIColor *cellAccessoryColor;
@property(readonly, nonatomic) UIColor *groupedDividerColor;
@property(readonly, nonatomic) UIColor *dividerColor;
@property(readonly, nonatomic) UIColor *shadowColor;
@property(readonly, nonatomic) UIColor *handleColor;
@property(readonly, nonatomic) UIColor *highlightBackgroundColor;
@property(readonly, nonatomic) UIColor *appBackgroundColor;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) UIColor *textDetailsColor;
@property(readonly, nonatomic) UIColor *textColor;
@end

