//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterAppearance/NSObject-Protocol.h>

@class UIFont;

@protocol TFNUIFontGroup <NSObject>
@property(readonly, nonatomic) UIFont *navSubtitleFont;
@property(readonly, nonatomic) UIFont *navTitleFont;
@end

