//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterAppearance/NSObject-Protocol.h>

@class UIColor;

@protocol TFNUIColorPalette <NSObject>
@property(readonly, nonatomic) UIColor *selectedCheckmarkColor;
@property(readonly, nonatomic) UIColor *dataViewModalBackgroundColor;
@property(readonly, nonatomic) UIColor *dataViewBackgroundColor;
@property(readonly, nonatomic) UIColor *groupedCellBorderColor;
@property(readonly, nonatomic) UIColor *cellAccessoryColor;
@property(readonly, nonatomic) UIColor *cellSeparatorColor;
@property(readonly, nonatomic) UIColor *highlightCellBackgroundColor;
@property(readonly, nonatomic) UIColor *cellBackgroundColor;
@property(readonly, nonatomic) UIColor *textDetailsColor;
@property(readonly, nonatomic) UIColor *textColor;
@end

