//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, TFSDatabaseUIApplicationLink;
@protocol TFSLogger, TFSScribeErrorDelegate;

@interface TFSScribeConfiguration : NSObject
{
    NSURL *_storeURL;
    TFSDatabaseUIApplicationLink *_applicationLink;
    double _shelfLife;
    id <TFSScribeErrorDelegate> _errorDelegate;
    id <TFSLogger> _debugLogger;
}

+ (id)configurationWithStoreURL:(id)arg1 applicationLink:(id)arg2 shelfLife:(double)arg3 errorDelegate:(id)arg4 debugLogger:(id)arg5;
+ (id)configurationWithStoreURL:(id)arg1 applicationLink:(id)arg2 errorDelegate:(id)arg3 debugLogger:(id)arg4;
+ (id)inMemoryConfigurationWithShelfLife:(double)arg1 errorDelegate:(id)arg2 debugLogger:(id)arg3;
+ (id)inMemoryConfigurationWithErrorDelegate:(id)arg1 debugLogger:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <TFSLogger> debugLogger; // @synthesize debugLogger=_debugLogger;
@property(readonly, nonatomic) __weak id <TFSScribeErrorDelegate> errorDelegate; // @synthesize errorDelegate=_errorDelegate;
@property(readonly, nonatomic) double shelfLife; // @synthesize shelfLife=_shelfLife;
@property(readonly, nonatomic) TFSDatabaseUIApplicationLink *applicationLink; // @synthesize applicationLink=_applicationLink;
@property(readonly, nonatomic) NSURL *storeURL; // @synthesize storeURL=_storeURL;
- (id)initWithStoreURL:(id)arg1 applicationLink:(id)arg2 shelfLife:(double)arg3 errorDelegate:(id)arg4 debugLogger:(id)arg5;

@end

