//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterCore/TFSTwitterOnboardingSubtask.h>

@class NSDictionary, NSString, TFSTwitterOnboardingHeader, TFSTwitterOnboardingNavigationLink, TFSTwitterOnboardingRichText;

@interface TFSTwitterOnboardingEnterPasswordSubtask : TFSTwitterOnboardingSubtask
{
    _Bool _skipPasswordValidation;
    _Bool _showPasswordConfirmation;
    TFSTwitterOnboardingHeader *_header;
    NSString *_name;
    NSString *_email;
    NSString *_username;
    NSString *_phoneNumber;
    long long _userIdentifierDisplayType;
    NSString *_hint;
    NSString *_passwordConfirmationHint;
    TFSTwitterOnboardingNavigationLink *_nextLink;
    TFSTwitterOnboardingNavigationLink *_skipLink;
    TFSTwitterOnboardingRichText *_passwordConfirmationMismatchMessage;
}

+ (long long)version;
+ (id)typeNames;
- (void).cxx_destruct;
@property(readonly, nonatomic) TFSTwitterOnboardingRichText *passwordConfirmationMismatchMessage; // @synthesize passwordConfirmationMismatchMessage=_passwordConfirmationMismatchMessage;
@property(readonly, nonatomic, getter=shouldShowPasswordConfirmation) _Bool showPasswordConfirmation; // @synthesize showPasswordConfirmation=_showPasswordConfirmation;
@property(readonly, nonatomic, getter=shouldSkipPasswordValidation) _Bool skipPasswordValidation; // @synthesize skipPasswordValidation=_skipPasswordValidation;
@property(readonly, nonatomic) TFSTwitterOnboardingNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) TFSTwitterOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) NSString *passwordConfirmationHint; // @synthesize passwordConfirmationHint=_passwordConfirmationHint;
@property(readonly, nonatomic) NSString *hint; // @synthesize hint=_hint;
@property(readonly, nonatomic) long long userIdentifierDisplayType; // @synthesize userIdentifierDisplayType=_userIdentifierDisplayType;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) TFSTwitterOnboardingHeader *header; // @synthesize header=_header;
@property(readonly, nonatomic) NSDictionary *userIdentifiers;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

