//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterCore/TFSTwitterUserReference.h>

@class NSString;

@interface TFSTwitterUserReference (T1Sharing)
- (id)_t1_twitterURLForShareWithSParam:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *twitterURLForViber;
@property(readonly, copy, nonatomic) NSString *twitterURLForLine;
@property(readonly, copy, nonatomic) NSString *twitterURLForTelegram;
@property(readonly, copy, nonatomic) NSString *twitterURLForGmail;
@property(readonly, copy, nonatomic) NSString *twitterURLForWhatsApp;
@property(readonly, copy, nonatomic) NSString *twitterURLForFacebookMessenger;
@property(readonly, copy, nonatomic) NSString *twitterURLForShareToSnap;
@property(readonly, copy, nonatomic) NSString *twitterURLForMessage;
@property(readonly, copy, nonatomic) NSString *twitterURLForCopy;
@property(readonly, copy, nonatomic) NSString *twitterURLForEmail;
@property(readonly, copy, nonatomic) NSString *twitterURLForShare;
@end

