//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TFSURTImageVariant, TFSURTRichText;

@interface TFSTwitterForwardPivot : NSObject
{
    // Error parsing type: , name: forwardPivot
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) TFSURTRichText *forwardPivotSubtext;
@property(nonatomic, readonly) NSString *forwardPivotDisplayType;
@property(nonatomic, readonly) NSString *forwardPivotLandingUrlString;
@property(nonatomic, readonly) NSString *forwardPivotBadgeTextColorName;
@property(nonatomic, readonly) NSString *forwardPivotBadgeText;
@property(nonatomic, readonly) TFSURTRichText *forwardPivotText;
@property(nonatomic, readonly) TFSURTImageVariant *forwardPivotImageVariant;
@property(nonatomic, readonly) _Bool hasSoftIntervention;

@end

