//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TFSTwitterAPI/NSCopying-Protocol.h>

@interface TFSTwitterAPIGraphQLConfiguration : NSObject <NSCopying>
{
    _Bool _tweetResultEnabled;
    _Bool _birdwatchConsumptionEnabled;
    _Bool _identityBadgingEnabled;
}

+ (id)defaultConfiguration;
@property(readonly, nonatomic, getter=isIdentityBadgingEnabled) _Bool identityBadgingEnabled; // @synthesize identityBadgingEnabled=_identityBadgingEnabled;
@property(readonly, nonatomic, getter=isBirdwatchConsumptionEnabled) _Bool birdwatchConsumptionEnabled; // @synthesize birdwatchConsumptionEnabled=_birdwatchConsumptionEnabled;
@property(readonly, nonatomic, getter=isTweetResultEnabled) _Bool tweetResultEnabled; // @synthesize tweetResultEnabled=_tweetResultEnabled;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTweetResultEnabled:(_Bool)arg1 birdwatchConsumptionEnabled:(_Bool)arg2 identityBadgingEnabled:(_Bool)arg3;

@end

