//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TwitterImagePipeline/TIPImageCache-Protocol.h>
#import <TwitterImagePipeline/TIPInspectableCache-Protocol.h>
#import <TwitterImagePipeline/TIPLRUCacheDelegate-Protocol.h>

@class NSString, TIPGlobalConfiguration, TIPLRUCache;

@interface TIPImageMemoryCache : NSObject <TIPLRUCacheDelegate, TIPImageCache, TIPInspectableCache>
{
    TIPGlobalConfiguration *_globalConfig;
    TIPLRUCache *_manifest;
    long long _atomicTotalCost;
}

- (void).cxx_destruct;
@property long long atomicTotalCost; // @synthesize atomicTotalCost=_atomicTotalCost;
@property(readonly, nonatomic) TIPLRUCache *manifest; // @synthesize manifest=_manifest;
- (void)inspect:(CDUnknownBlockType)arg1;
- (void)tip_cache:(id)arg1 didEvictEntry:(id)arg2;
- (void)clearAllImages:(CDUnknownBlockType)arg1;
- (void)clearImageWithIdentifier:(id)arg1;
- (void)touchImageWithIdentifier:(id)arg1;
- (void)updateImageEntry:(id)arg1 forciblyReplaceExisting:(_Bool)arg2;
- (id)imageEntryForIdentifier:(id)arg1 targetDimensions:(struct CGSize)arg2 targetContentMode:(long long)arg3 decoderConfigMap:(id)arg4;
- (void)_tip_memoryCache_didReceiveMemoryWarning:(id)arg1;
- (void)dealloc;
- (id)init;
@property(readonly, nonatomic) long long cacheType;
@property(readonly, nonatomic) unsigned long long totalCost;
- (void)_memoryCache_inspect:(CDUnknownBlockType)arg1;
- (void)_memoryCache_didEvictEntry:(id)arg1;
- (_Bool)_memoryCache_updateEntry:(id)arg1 withCompleteImageData:(id)arg2 context:(id)arg3;
- (_Bool)_memoryCache_updateEntry:(id)arg1 withPartialImage:(id)arg2 context:(id)arg3;
- (void)_memoryCache_updateByteCountsAdded:(unsigned long long)arg1 removed:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

