//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterImagePipeline/TIPSafeOperation.h>

#import <TwitterImagePipeline/TIPImageDownloadDelegate-Protocol.h>

@class NSArray, NSDictionary, NSError, NSObject, NSString, TIPImageContainer, TIPImageFetchDelegateDeallocHandler, TIPImageFetchMetrics, TIPImageFetchOperationNetworkStepContext, TIPImagePipeline;
@protocol OS_dispatch_queue, TIPImageFetchDelegate, TIPImageFetchProgressiveLoadingPolicy, TIPImageFetchRequest, TIPImageFetchResult, TIPImageFetchTransformer;

@interface TIPImageFetchOperation : TIPSafeOperation <TIPImageDownloadDelegate>
{
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    TIPImageFetchMetrics *_metricsInternal;
    // Error parsing type: Aq, name: _state
    unsigned long long _enqueueTime;
    unsigned long long _startTime;
    unsigned long long _finishTime;
    struct CGSize _targetDimensions;
    long long _targetContentMode;
    long long _loadingSources;
    NSDictionary *_progressiveLoadingPolicies;
    id <TIPImageFetchProgressiveLoadingPolicy> _progressiveLoadingPolicy;
    id <TIPImageFetchTransformer> _transformer;
    NSString *_transfomerIdentifier;
    NSArray *_observers;
    NSDictionary *_decoderConfigMap;
    TIPImageFetchOperationNetworkStepContext *_networkContext;
    unsigned long long _progressiveRenderCount;
    long long _enqueuedPriority;
    struct {
        unsigned int cancelled:1;
        unsigned int isEarlyCompletion:1;
        unsigned int invalidRequest:1;
        unsigned int wasEnqueued:1;
        unsigned int didStart:1;
        unsigned int didReceiveFirstByte:1;
        unsigned int shouldJumpToResumingDownload:1;
        unsigned int wasResumedDownload:1;
        unsigned int progressivePermissionValidated:1;
        unsigned int permitsProgressiveLoading:1;
        unsigned int delegateSupportsAttemptWillStartCallbacks:1;
        unsigned int didExtractStorageInfo:1;
        unsigned int didExtractTargetInfo:1;
        unsigned int didReceiveFirstAnimatedFrame:1;
        unsigned int transitioningToFinishedState:1;
        unsigned int progressiveImageWasTransformed:1;
        unsigned int previewImageWasTransformed:1;
        unsigned int finalImageWasTransformed:1;
        unsigned int shouldSkipRenderedCacheStore:1;
    } _flags;
    float _progress;
    id <TIPImageFetchRequest> _request;
    id <TIPImageFetchDelegate> _delegate;
    TIPImagePipeline *_imagePipeline;
    id <TIPImageFetchResult> _previewResult;
    id <TIPImageFetchResult> _progressiveResult;
    id <TIPImageFetchResult> _finalResult;
    NSString *_networkLoadImageType;
    unsigned long long _progressiveFrameCount;
    NSError *_error;
    TIPImageFetchMetrics *_metrics;
    id _context;
    id <TIPImageFetchDelegate> _strongDelegate;
    TIPImageFetchDelegateDeallocHandler *_delegateHandler;
    NSError *_operationError;
    TIPImageContainer *_previewImageContainerRaw;
    TIPImageContainer *_finalImageContainerRaw;
    struct CGSize _networkImageOriginalDimensions;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TIPImageContainer *finalImageContainerRaw; // @synthesize finalImageContainerRaw=_finalImageContainerRaw;
@property(retain, nonatomic) TIPImageContainer *previewImageContainerRaw; // @synthesize previewImageContainerRaw=_previewImageContainerRaw;
@property(retain, nonatomic) NSError *operationError; // @synthesize operationError=_operationError;
@property __weak TIPImageFetchDelegateDeallocHandler *delegateHandler; // @synthesize delegateHandler=_delegateHandler;
@property(retain) id <TIPImageFetchDelegate> strongDelegate; // @synthesize strongDelegate=_strongDelegate;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(readonly, nonatomic) TIPImageFetchMetrics *metrics; // @synthesize metrics=_metrics;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) unsigned long long progressiveFrameCount; // @synthesize progressiveFrameCount=_progressiveFrameCount;
@property(nonatomic) struct CGSize networkImageOriginalDimensions; // @synthesize networkImageOriginalDimensions=_networkImageOriginalDimensions;
@property(copy, nonatomic) NSString *networkLoadImageType; // @synthesize networkLoadImageType=_networkLoadImageType;
@property(retain, nonatomic) id <TIPImageFetchResult> finalResult; // @synthesize finalResult=_finalResult;
@property(retain, nonatomic) id <TIPImageFetchResult> progressiveResult; // @synthesize progressiveResult=_progressiveResult;
@property(retain, nonatomic) id <TIPImageFetchResult> previewResult; // @synthesize previewResult=_previewResult;
@property(readonly, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
@property __weak id <TIPImageFetchDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <TIPImageFetchRequest> request; // @synthesize request=_request;
- (void)_hydrateNewContext:(id)arg1 imageURL:(id)arg2 placeholder:(_Bool)arg3;
- (void)imageDownload:(id)arg1 didCompleteWithPartialImage:(id)arg2 lastModified:(id)arg3 byteSize:(unsigned long long)arg4 imageType:(id)arg5 image:(id)arg6 imageData:(id)arg7 imageRenderLatency:(double)arg8 statusCode:(long long)arg9 error:(id)arg10;
- (void)imageDownload:(id)arg1 didAppendBytes:(unsigned long long)arg2 toPartialImage:(id)arg3 result:(long long)arg4;
- (void)imageDownload:(id)arg1 didResetFromPartialImage:(id)arg2;
- (void)imageDownloadDidStart:(id)arg1;
- (id)regenerateImageDownloadTemporaryFileForImageDownload:(id)arg1;
- (id)imageDownloadRequest;
- (id)imageDownloadDelegateQueue;
- (void)waitUntilFinishedWithoutBlockingRunLoop;
- (void)waitUntilFinished;
- (_Bool)supportsLoadingFromSource:(long long)arg1;
- (_Bool)supportsLoadingFromRenderedCache;
- (void)willEnqueue;
- (void)handleEarlyLoadOfDirtyImageEntry:(id)arg1 transformed:(_Bool)arg2 sourceImageDimensions:(struct CGSize)arg3;
- (void)completeOperationEarlyWithImageEntry:(id)arg1 transformed:(_Bool)arg2 sourceImageDimensions:(struct CGSize)arg3;
- (void)start;
- (_Bool)isAsynchronous;
- (_Bool)isConcurrent;
- (_Bool)isCancelled;
- (_Bool)isExecuting;
- (_Bool)isFinished;
- (void)cancelAndDiscardDelegate;
- (void)cancel;
- (void)discardDelegate;
@property(nonatomic) long long priority;
@property long long qualityOfService;
@property long long queuePriority;
@property(nonatomic) long long state;
@property(readonly) double timeSpentExecuting;
@property(readonly) double timeSpentIdleInQueue;
- (id)imageURL;
- (id)imageIdentifier;
- (id)transformerIdentifier;
- (void)_extractBasicRequestInfo;
- (void)_clearDelegateHandler;
- (void)_initializeDelegate:(id)arg1;
- (id)initWithImagePipeline:(id)arg1 request:(id)arg2 delegate:(id)arg3;
- (id)init;
- (void)_executeBackgroundWork:(CDUnknownBlockType)arg1;
- (void)_background_executeDelegateWork:(CDUnknownBlockType)arg1;
- (void)_background_propagateFinalRenderedImage:(long long)arg1;
- (void)_background_propagateFinalImageData:(id)arg1 loadSource:(long long)arg2;
- (void)_background_propagatePreviewImage:(long long)arg1;
- (void)_background_propagatePartialImage:(id)arg1 lastModified:(id)arg2 wasResumed:(_Bool)arg3;
- (id)_background_createCacheEntryFromPartialImage:(id)arg1 lastModified:(id)arg2 imageURL:(id)arg3;
- (id)_background_createCacheEntryUsingRawImage:(_Bool)arg1 permitPreviewFallback:(_Bool)arg2 didFallback:(out _Bool *)arg3;
- (id)_background_getFirstFrameOfAnimatedImageIfNotYetProvided:(id)arg1;
- (id)_background_getNextProgressiveImageWithAppendResult:(long long)arg1 partialImage:(id)arg2 renderCount:(unsigned long long)arg3;
- (void)_background_processContinuedPartialEntry:(id)arg1 URL:(id)arg2 loadSource:(long long)arg3;
- (id)_background_transformAndScaleImage:(id)arg1 progress:(float)arg2 didTransform:(out _Bool *)arg3;
- (id)_background_transformAndScaleImageContainer:(id)arg1 progress:(float)arg2 didTransform:(out _Bool *)arg3;
- (void)_background_handlePartialDiskEntry:(id)arg1 tryOtherPipelineDiskCachesIfNeeded:(_Bool)arg2;
- (void)_background_handleCompletedDiskEntry:(id)arg1;
- (void)_background_handlePartialMemoryEntry:(id)arg1;
- (void)_background_handleCompletedMemoryEntry:(id)arg1;
- (void)_background_updateProgress:(float)arg1;
- (void)_background_updateProgressiveImage:(id)arg1 transformed:(_Bool)arg2 renderLatency:(double)arg3 URL:(id)arg4 progress:(float)arg5 sourcePartialImage:(id)arg6 loadSource:(long long)arg7;
- (void)_background_updateFirstAnimatedImageFrame:(id)arg1 renderLatency:(double)arg2 URL:(id)arg3 progress:(float)arg4 sourcePartialImage:(id)arg5 loadSource:(long long)arg6;
- (void)_background_updatePreviewImageWithCacheEntry:(id)arg1 loadSource:(long long)arg2;
- (void)_background_postDidFinishDownloadingImageOfType:(id)arg1 sizeInBytes:(unsigned long long)arg2;
- (void)_background_postDidStartDownload;
- (void)_background_postDidFinish;
- (void)_background_postDidStart;
- (void)_background_updateFinalImage:(id)arg1 imageData:(id)arg2 renderLatency:(double)arg3 URL:(id)arg4 loadSource:(long long)arg5 networkImageType:(id)arg6 networkByteCount:(unsigned long long)arg7 placeholder:(_Bool)arg8;
- (void)_background_updateFailureToLoadFinalImage:(id)arg1 updateMetrics:(_Bool)arg2;
- (void)_background_loadFromNetwork;
- (void)_background_loadFromNextAdditionalCache:(id)arg1 imageURL:(id)arg2;
- (void)_background_loadFromAdditional;
- (void)_background_loadFromOtherPipelineDisk;
- (void)_background_loadFromDisk;
- (void)_background_loadFromMemory;
- (void)_background_loadFromNextSource;
- (void)_background_dispatchLoadStarted:(long long)arg1;
- (void)_background_setFinalStateAfterFlushingDelegate:(long long)arg1;
- (void)_background_clearNetworkContextVariables;
- (void)_background_validateProgressiveSupportWithPartialImage:(id)arg1;
- (void)_background_extractTargetInfo;
- (void)_background_extractAdvancedRequestInfo;
- (void)_background_extractStorageInfo;
- (void)_background_extractObservers;
- (_Bool)_background_shouldAbort;
- (void)_background_start;
- (void)_diskCache_completeLoadFromOtherPipelineDisk:(id)arg1 imageContainer:(id)arg2 URL:(id)arg3 latency:(double)arg4 placeholder:(_Bool)arg5;
- (_Bool)_diskCache_attemptLoadFromOtherPipelineDisk:(id)arg1 startMachTime:(unsigned long long)arg2;
- (void)_diskCache_loadFromOtherPipelines:(id)arg1 startMachTime:(unsigned long long)arg2;
- (id)associatedDownloadContext;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

