//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableSet, NSSet;
@protocol OS_dispatch_queue, TLSLoggingServiceDelegate;

@interface TLSLoggingService : NSObject
{
    NSObject<OS_dispatch_queue> *_transactionQueue;
    NSObject<OS_dispatch_queue> *_loggingQueue;
    double _baseTimestamp;
    NSMutableSet *_streamsM;
    NSObject<OS_dispatch_queue> *_quickFilterQueue;
    long long _quickFilterLevels;
    NSMutableSet *_quickFilterOffChannelsM;
    unsigned long long _quickFilterOutputStreamCount;
    unsigned long long _maximumSafeMessageLength;
    id <TLSLoggingServiceDelegate> _delegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property __weak id <TLSLoggingServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long maximumSafeMessageLength; // @synthesize maximumSafeMessageLength=_maximumSafeMessageLength;
- (_Bool)_canLogWithLevel:(long long)arg1 channel:(id)arg2 context:(id)arg3;
- (long long)_transaction_filterLogStream:(id)arg1 level:(long long)arg2 channel:(id)arg3 context:(id)arg4;
- (void)_transaction_logExecuteWithTimestamp:(double)arg1 level:(long long)arg2 channel:(id)arg3 file:(id)arg4 function:(id)arg5 line:(long long)arg6 context:(id)arg7 threadId:(unsigned int)arg8 threadName:(id)arg9 message:(id)arg10;
- (void)_logDispatchWithLevel:(long long)arg1 channel:(id)arg2 file:(id)arg3 function:(id)arg4 line:(long long)arg5 context:(id)arg6 options:(long long)arg7 format:(id)arg8 arguments:(char *)arg9;
- (void)_nonquickFilter_resetQuickFilter:(unsigned long long)arg1;
- (void)logWithLevel:(long long)arg1 channel:(id)arg2 file:(id)arg3 function:(id)arg4 line:(long long)arg5 contextObject:(id)arg6 options:(long long)arg7 message:(id)arg8;
- (void)addOutputStream:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)retrieveLoggedDataFromOutputStream:(id)arg1 maxBytes:(unsigned long long)arg2;
- (id)outputStreamsThatSupportLoggedDataRetrieval;
- (void)flush;
- (void)dispatchAsynchronousTransaction:(CDUnknownBlockType)arg1;
- (void)dispatchSynchronousTransaction:(CDUnknownBlockType)arg1;
- (void)updateOutputStream:(id)arg1;
@property(readonly) NSSet *outputStreams;
- (void)removeOutputStream:(id)arg1;
@property(readonly, nonatomic) NSDate *startupTimestamp;

@end

